version: '2'
services:
  postgres:
    image: postgres:12.8
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=b_admin
      - POSTGRES_PASSWORD=Password12345
      - POSTGRES_DB=b_dev_db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

# Remember when you first setup the container you will need to run: CREATE EXTENSION IF NOT EXISTS "uuid-ossp";